// Sidebar menu configuration for scalability
export const sidebarMenuConfig = [
    {
        id: "gmisl",
        label: "GMISL ( Sales & Logistic )",
        icon: "ShoppingCart",
        color: "text-white",
        children: [
            {
                id: "utility",
                label: "Utility",
                icon: "Wrench",
                children: [
                    {
                        id: "tickets",
                        label: "Tickets",
                        icon: "Ticket",
                        route: "/tickets",
                        module_key: "utility.tickets",
                    },
                    {
                        id: "request-access",
                        label: "Request Access",
                        icon: "UserPlus",
                        route: "/request-access",
                        module_key: "utility.request_access",
                    },
                    {
                        id: "date-code",
                        label: "No Identity",
                        icon: "Calendar",
                        route: "/gmisl/utility/date-code",
                        module_key: "utility.date_code",
                    },
                    {
                        id: "check-inline",
                        label: "Check Inline",
                        icon: "CheckSquare",
                        route: "/check-inline",
                        module_key: "utility.check_inline",
                    },
                    {
                        id: "berita-acara",
                        label: "Berita Acara",
                        icon: "FileText",
                        route: "/gmisl/utility/berita-acara",
                        module_key: "utility.berita_acara",
                    },
                ],
            },
        ],
    },
    {
        id: "gmium",
        label: "GMIUM ( Utility Management )",
        icon: "Wrench",
        color: "text-white",
        children: [
            {
                id: "plugging",
                label: "Plugging",
                icon: "Wrench",
                route: "/gmium/plugging",
                module_key: "gmium.plugging",
            },
            {
                id: "plugging-approval",
                label: "Plugging Approval",
                icon: "CheckCircle",
                route: "/gmium/plugging/approval",
                module_key: "gmium.plugging",
            },
            {
                id: "resource-monitoring",
                label: "Resource Monitoring",
                icon: "Clipboard",
                children: [
                    {
                        id: "electricity",
                        label: "Electricity",
                        icon: "Clock",
                        children: [
                            {
                                id: "standard-meter",
                                label: "Standard Meter",
                                icon: "FileText",
                                route: "/gmium/resource-monitoring/electricity/standard-meter",
                                module_key: "gmium.resource_monitoring.electricity.standard_meter",
                            },
                            {
                                id: "hv-meter",
                                label: "HV Meter",
                                icon: "Activity",
                                route: "/gmium/resource-monitoring/electricity/hv-meter",
                                module_key: "gmium.resource_monitoring.electricity.hv_meter",
                            },
                        ],
                    },
                    {
                        id: "water-meter",
                        label: "Water Meter",
                        icon: "FileText",
                        route: "/gmium/resource-monitoring/water-meter",
                        module_key: "gmium.resource_monitoring.water_meter",
                    },
                ],
            },
            {
                id: "utility-report",
                label: "Utility Report",
                icon: "FileText",
                route: "/gmium/utility-report",
                module_key: "gmium.utility_report",
            },
        ],
    },
    {
        id: "gmi-visitor-permit",
        label: "GMIVP ( Visitor & Permit )",
        icon: "Users",
        color: "text-white",
        children: [
            {
                id: "visitor-form",
                label: "Visitor Form",
                icon: "User",
                route: "/gmi-visitor-permit/visitor-form",
                module_key: "gmi_visitor_permit.visitor_form",
            },
            {
                id: "exit-permit",
                label: "Exit Permit (Surat Izin Keluar)",
                icon: "FileText",
                route: "/gmi-visitor-permit/exit-permit",
                module_key: "gmi_visitor_permit.exit_permit",
            },
        ],
    },
    {
        id: "gmiic",
        label: "GMIIC ( Inspection & Checklist )",
        icon: "Clipboard",
        color: "text-white",
        children: [
            {
                id: "gmiic-checklist",
                label: "Checklist",
                icon: "CheckSquare",
                route: "/gmiic/checklist",
                module_key: "gmiic.checklist",
            },
        ],
    },
    {
        id: "gmihr",
        label: "GMIHR ( Human Resources )",
        icon: "Users",
        color: "text-white",
        children: [
            {
                id: "time-attendance",
                label: "Time & Attendance",
                icon: "Clock",
                children: [
                    {
                        id: "attendance-log",
                        label: "Attendance Log",
                        icon: "FileText",
                        route: "/attendance-log",
                        module_key: "gmihr.attendance.log",
                    },
                    {
                        id: "leave-permission",
                        label: "Leave & Permission",
                        icon: "Calendar",
                        route: "/leave-permission",
                        module_key: "gmihr.attendance.leave_permission",
                    },
                    {
                        id: "roster",
                        label: "Roster",
                        icon: "Users",
                        children: [
                            {
                                id: "roster-upload",
                                label: "Upload",
                                icon: "Upload",
                                route: "/roster/upload",
                                module_key: "gmihr.payroll.roster.upload",
                            },
                            {
                                id: "roster-list",
                                label: "List",
                                icon: "List",
                                route: "/roster/list",
                                module_key: "gmihr.payroll.roster.list",
                            },
                        ],
                    },
                    {
                        id: "overtime",
                        label: "Overtime",
                        icon: "PlusCircle",
                        route: "/overtime",
                        module_key: "gmihr.attendance.overtime",
                    },
                    {
                        id: "the-days",
                        label: "The Days",
                        icon: "CalendarDays",
                        route: "/the-days",
                        module_key: "gmihr.attendance.the_days",
                    },
                ],
            },
            {
                id: "payroll",
                label: "Payroll",
                icon: "Clipboard",
                color: "text-yellow-300",
                children: [
                    {
                        id: "salary",
                        label: "Salary",
                        icon: "DollarSign",
                        route: "/salary",
                        module_key: "gmihr.payroll.salary",
                    },
                    {
                        id: "payslip",
                        label: "Payslip",
                        icon: "File",
                        route: "/payslip",
                        module_key: "gmihr.payroll.payslip",
                    },
                ],
            },
            {
                id: "device-integration",
                label: "Device Integration",
                icon: "Monitor",
                children: [
                      {
                          id: "fingerprint",
                          label: "Fingerprint",
                          icon: "Fingerprint",
                          route: "/fingerprint",
                          module_key: "gmihr.device.fingerprint",
                      },
                  ],
              },
        ],
    },
    {
        id: "masterData",
        label: "Master Data",
        icon: "Database",
        color: "text-slate-300",
        module_key: "gmisl.master_data",
        children: [
            {
                id: "customer",
                label: "Customer",
                icon: "User",
                route: "/master-data/customer",
                module_key: "gmisl.master_data.customer",
            },
            {
                id: "employee",
                label: "Employee",
                icon: "Users",
                route: "/master-data/employee",
                module_key: "gmisl.master_data.employee",
            },
            {
                id: "department",
                label: "Department",
                icon: "Building",
                route: "/master-data/department",
                module_key: "gmisl.master_data.department",
            },
            {
                id: "position",
                label: "Position",
                icon: "Briefcase",
                route: "/master-data/position",
                module_key: "gmisl.master_data.position",
            },
            {
                id: "vehicle-type",
                label: "Jenis Kendaraan",
                icon: "Truck",
                route: "/master-data/vehicle-type",
                module_key: "gmisl.master_data.vehicle_type",
            },
        ],
    },
    {
        id: "control",
        label: "Control Panel",
        icon: "Settings",
        color: "text-slate-300",
        children: [
            {
                id: "users",
                label: "Users",
                icon: "User",
                route: "/control-panel/user",
                module_key: "control.users",
            },
            {
                id: "modul-control",
                label: "Modul Control",
                icon: "Server",
                route: "/control-panel/module-control",
                module_key: "control.module",
            },
            {
                id: "logs",
                label: "Logs",
                icon: "FileText",
                route: "/control-panel/logs",
                module_key: "control.logs",
            },
        ],
    },
];

