// Sidebar menu configuration for scalability
export const sidebarMenuConfig = [
    {
        id: "gmisl",
        label: "GMISL ( Sales & Logistic )",
        icon: "ShoppingCart",
        color: "text-white",
        children: [
            {
                id: "utility",
                label: "Utility",
                icon: "Wrench",
                children: [
                    {
                        id: "tickets",
                        label: "Tickets",
                        icon: "Ticket",
                        route: "/tickets",
                        module_key: "utility.tickets",
                    },
                    {
                        id: "request-access",
                        label: "Request Access",
                        icon: "UserPlus",
                        route: "/request-access",
                        module_key: "utility.request_access",
                    },
                    {
                        id: "date-code",
                        label: "No Identity",
                        icon: "Calendar",
                        route: "/gmisl/utility/date-code",
                        module_key: "utility.date_code",
                    },
                    {
                        id: "check-inline",
                        label: "Check Inline",
                        icon: "CheckSquare",
                        route: "/check-inline",
                        module_key: "utility.check_inline",
                    },
                    {
                        id: "berita-acara",
                        label: "Berita Acara",
                        icon: "FileText",
                        route: "/gmisl/utility/berita-acara",
                        module_key: "utility.berita_acara",
                    },
                    {
                        id: "stock-card",
                        label: "Stock Card",
                        icon: "Package",
                        route: "/gmisl/utility/stock-card",
                        module_key: "utility.stock_card",
                    },
                ],
            },
            {
                id: "cross-odoo",
                label: "Cross Odoo",
                icon: "Layers",
                children: [
                    {
                        id: "cross-odoo-stock-card",
                        label: "Stock Card",
                        icon: "Package",
                        route: "/gmisl/cross-odoo/stock-card",
                        module_key: "utility.stock_card",
                    },
                ],
            },
            {
                id: "procurement",
                label: "Procurement",
                icon: "ShoppingBag",
                children: [
                    {
                        id: "purchase-requisition",
                        label: "Purchase Requisition",
                        icon: "FileText",
                        route: "/gmisl/procurement/purchase-requisition",
                        module_key: "gmisl.procurement.purchase_requisition",
                    },
                    {
                        id: "purchase-order",
                        label: "Purchase Order",
                        icon: "ShoppingCart",
                        route: "/gmisl/procurement/purchase-order",
                        module_key: "gmisl.procurement.purchase_order",
                    },
                    {
                        id: "procurement-approval",
                        label: "Approval",
                        icon: "CheckCheck",
                        route: "/gmisl/procurement/approval",
                        module_key: "gmisl.procurement.approval",
                        department_codes: ["OWNER"],
                    },
                ],
            },
            {
                id: "tools",
                label: "Tools",
                icon: "Wrench",
                children: [
                    {
                        id: "compress-pdf",
                        label: "Compress PDF",
                        icon: "FileText",
                        route: "/gmisl/tools/compress-pdf",
                        module_key: "tools.compress_pdf",
                    },
                    {
                        id: "merge-pdf",
                        label: "Merge PDF",
                        icon: "Files",
                        route: "/gmisl/tools/merge-pdf",
                        module_key: "tools.merge_pdf",
                    },
                    {
                        id: "split-pdf",
                        label: "Split PDF",
                        icon: "Scissors",
                        route: "/gmisl/tools/split-pdf",
                        module_key: "tools.split_pdf",
                    },
                ],
            },
        ],
    },
    {
        id: "gmi-visitor-permit",
        label: "GMIVP ( Visitor & Permit )",
        icon: "Users",
        color: "text-white",
        children: [
            {
                id: "visitor-form",
                label: "Visitor Form",
                icon: "User",
                route: "/gmi-visitor-permit/visitor-form",
                module_key: "gmi_visitor_permit.visitor_form",
            },
            {
                id: "exit-permit",
                label: "Exit Permit (Surat Izin Keluar)",
                icon: "FileText",
                route: "/gmi-visitor-permit/exit-permit",
                module_key: "gmi_visitor_permit.exit_permit",
            },
        ],
    },
    {
        id: "gmiic",
        label: "GMIIC ( Inspection & Checklist )",
        icon: "Clipboard",
        color: "text-white",
        children: [
            {
                id: "gmiic-checklist",
                label: "Checklist",
                icon: "CheckSquare",
                route: "/gmiic/checklist",
                module_key: "gmiic.checklist",
            },
        ],
    },
    {
        id: "gmihr",
        label: "GMIHR ( Human Resources )",
        icon: "Users",
        color: "text-white",
        children: [
            {
                id: "time-attendance",
                label: "Time & Attendance",
                icon: "Clock",
                children: [
                    {
                        id: "attendance-log",
                        label: "Attendance Log",
                        icon: "FileText",
                        route: "/attendance-log",
                        module_key: "gmihr.attendance.log",
                    },
                    {
                        id: "absensi",
                        label: "Absensi",
                        icon: "Clock",
                        route: "/absensi",
                        module_key: "gmihr.attendance.absensi",
                    },
                    {
                        id: "attendance-approval",
                        label: "Attendance Approval",
                        icon: "CheckCheck",
                        route: "/attendance-approval",
                        module_key: "gmihr.attendance.approval",
                    },
                    {
                        id: "leave-permission",
                        label: "Leave & Permission",
                        icon: "Calendar",
                        route: "/leave-permission",
                        module_key: "gmihr.attendance.leave_permission",
                    },
                    {
                        id: "roster",
                        label: "Roster",
                        icon: "Users",
                        children: [
                            {
                                id: "roster-upload",
                                label: "Upload",
                                icon: "Upload",
                                route: "/roster/upload",
                                module_key: "gmihr.payroll.roster.upload",
                            },
                            {
                                id: "roster-list",
                                label: "List",
                                icon: "List",
                                route: "/roster/list",
                                module_key: "gmihr.payroll.roster.list",
                            },
                        ],
                    },
                    {
                        id: "overtime",
                        label: "Overtime",
                        icon: "PlusCircle",
                        route: "/overtime",
                        module_key: "gmihr.attendance.overtime",
                    },
                    {
                        id: "the-days",
                        label: "The Days",
                        icon: "CalendarDays",
                        route: "/the-days",
                        module_key: "gmihr.attendance.the_days",
                    },
                ],
            },
            {
                id: "payroll",
                label: "Payroll",
                icon: "Clipboard",
                color: "text-yellow-300",
                children: [
                    {
                        id: "salary",
                        label: "Salary",
                        icon: "DollarSign",
                        route: "/salary",
                        module_key: "gmihr.payroll.salary",
                    },
                    {
                        id: "payslip",
                        label: "Payslip",
                        icon: "File",
                        route: "/payslip",
                        module_key: "gmihr.payroll.payslip",
                    },
                ],
            },
            {
                id: "device-integration",
                label: "Device Integration",
                icon: "Monitor",
                children: [
                    {
                        id: "fingerprint",
                        label: "Fingerprint",
                        icon: "Fingerprint",
                        route: "/fingerprint",
                        module_key: "gmihr.device.fingerprint",
                    },
                ],
            },
        ],
    },
    {
        id: "masterData",
        label: "Master Data",
        icon: "Database",
        color: "text-slate-300",
        module_key: "gmisl.master_data",
        children: [
            {
                id: "customer",
                label: "Customer",
                icon: "User",
                route: "/master-data/customer",
                module_key: "gmisl.master_data.customer",
            },
            {
                id: "supplier",
                label: "Supplier",
                icon: "Truck",
                route: "/master-data/supplier",
                module_key: "gmisl.procurement.purchase_requisition",
            },
            {
                id: "employee",
                label: "Employee",
                icon: "Users",
                route: "/master-data/employee",
                module_key: "gmisl.master_data.employee",
            },
            {
                id: "department",
                label: "Department",
                icon: "Building",
                route: "/master-data/department",
                module_key: "gmisl.master_data.department",
            },
            {
                id: "position",
                label: "Position",
                icon: "Briefcase",
                route: "/master-data/position",
                module_key: "gmisl.master_data.position",
            },
            {
                id: "vehicle-type",
                label: "Jenis Kendaraan",
                icon: "Truck",
                route: "/master-data/vehicle-type",
                module_key: "gmisl.master_data.vehicle_type",
            },
            {
                id: "stock-card-master",
                label: "Stock Card",
                icon: "Package",
                route: "/master-data/stock-card",
                module_key: "gmisl.master_data.stock_card",
            },
            {
                id: "stock-card-item-type",
                label: "Master Item Type",
                icon: "ListTree",
                route: "/master-data/stock-card-item-type",
                module_key: "gmisl.master_data.stock_card_item_type",
            },
            {
                id: "procurement-category",
                label: "Master Category",
                icon: "Folder",
                route: "/master-data/procurement-category",
                module_key: "gmisl.master_data.procurement_category",
            },
            {
                id: "stock-card-unit",
                label: "Master UoM",
                icon: "Ruler",
                route: "/master-data/stock-card-unit",
                module_key: "gmisl.master_data.stock_card_unit",
            },
            {
                id: "attendance-lock-area",
                label: "Area Absensi",
                icon: "Building",
                route: "/master-data/attendance-lock-area",
                module_key: "gmisl.master_data.attendance_lock_area",
            },
            {
                id: "procurement-master-item",
                label: "Master Item",
                icon: "Package",
                route: "/master-data/master-item",
                module_key: "gmisl.master_data.procurement_master_item",
            },
        ],
    },
    {
        id: "control",
        label: "Control Panel",
        icon: "Settings",
        color: "text-slate-300",
        children: [
            {
                id: "users",
                label: "Users",
                icon: "User",
                route: "/control-panel/user",
                module_key: "control.users",
            },
            {
                id: "modul-control",
                label: "Modul Control",
                icon: "Server",
                route: "/control-panel/module-control",
                module_key: "control.module",
            },
            {
                id: "logs",
                label: "Logs",
                icon: "FileText",
                route: "/control-panel/logs",
                module_key: "control.logs",
            },
            {
                id: "access-rules",
                label: "Access Rules",
                icon: "Shield",
                route: "/control-panel/access-rules",
                module_key: "control.access_rules",
            },
            {
                id: "database-backup",
                label: "Database Backup",
                icon: "Database",
                route: "/control-panel/database-backup",
                module_key: "control.database_backup",
            },
            {
                id: "tools",
                label: "Tools",
                icon: "Wrench",
                route: "/control-panel/tools",
                module_key: "control.tools",
            },
        ],
    },
];
