export const groupedLocationLabels = {
    pos_security: "Lantai 1 Depan Dan Luar",
    lantai_1_area_luar: "Lantai 1 Depan Dan Luar",
    lobby_lantai_1: "Lantai 1 Dalam",
    lantai_1_area_dalam: "Lantai 1 Dalam",
    loading_dock: "Lantai 1 Dalam",
    ruang_admin: "Lantai 1 Belakang",
    ruang_kontrol: "Lantai 1 Belakang",
    area_ruang_mesin: "Lantai 1 Belakang",
    lantai_1_area_belakang: "Lantai 1 Belakang",
    area_office_lantai_2: "Lantai 2 Office",
    lantai_2: "Lantai 2 Office",
    area_lantai_3: "Lantai 3 Office",
    lantai_3: "Lantai 3 Office",
};

export const groupedChecklistAreaLabels = {
    lantai_1_area_luar: groupedLocationLabels.lantai_1_area_luar,
    lantai_1_area_belakang: groupedLocationLabels.lantai_1_area_belakang,
    lantai_1_area_dalam: groupedLocationLabels.lantai_1_area_dalam,
    lantai_2: groupedLocationLabels.lantai_2,
    lantai_3: groupedLocationLabels.lantai_3,
    loading_dock: groupedLocationLabels.loading_dock,
    pos_security: "POS SECURITY",
    loading_dock_luar: "LOADING DOCK LUAR",
    travo_pln_depan: "TRAVO PLN DEPAN",
    tanah_kosong_dan_sekitar_bangunan: "TANAH KOSONG DAN SEKITAR BANGUNAN",
    travo_pln_belakang: "TRAVO PLN BELAKANG",
    genset: "GENSET",
    ruang_mesin_ruang_kontrol: "RUANG MESIN, RUANG KONTROL",
    sekitar_bangunan: "SEKITAR BANGUNAN",
    lobby_ruang_loker: "LOBBY, RUANG LOKER",
    loading_dock_dalam: "LOADING DOCK DALAM",
    anteroom_cold_storage: "ANTEROOM, COLD STORAGE",
    ruang_baterai: "RUANG BATERAI",
    ruang_admin: "RUANG ADMIN",
};

export const kotakP3KMonths = [
    { key: "jan", label: "Jan", number: 1 },
    { key: "feb", label: "Feb", number: 2 },
    { key: "mar", label: "Mar", number: 3 },
    { key: "apr", label: "Apr", number: 4 },
    { key: "may", label: "May", number: 5 },
    { key: "jun", label: "Jun", number: 6 },
    { key: "jul", label: "Jul", number: 7 },
    { key: "aug", label: "Aug", number: 8 },
    { key: "sep", label: "Sep", number: 9 },
    { key: "oct", label: "Oct", number: 10 },
    { key: "nov", label: "Nov", number: 11 },
    { key: "dec", label: "Dec", number: 12 },
];

export const kotakP3KItems = [
    { id: "kondisi_kotak_p3k", name: "Kondisi kotak P3K", quantity: "" },
    { id: "kasa_steril_terbungkus", name: "Kasa steril terbungkus", quantity: 20 },
    { id: "perban_5_cm", name: "Perban (lebar 5 cm)", quantity: 2 },
    { id: "perban_10_cm", name: "Perban (lebar 10 cm)", quantity: 2 },
    { id: "plester_1_25_cm", name: "Plester (lebar 1,25 cm)", quantity: 2 },
    { id: "plester_cepat", name: "Plester Cepat", quantity: 10 },
    { id: "kapas_25_gram", name: "Kapas (25 gram)", quantity: 1 },
    { id: "kain_segitiga", name: "Kain segitiga/mitela", quantity: 2 },
    { id: "gunting", name: "Gunting", quantity: 1 },
    { id: "peniti", name: "Peniti", quantity: 12 },
    { id: "sarung_tangan", name: "Sarung tangan sekali pakai", quantity: 2 },
    { id: "masker", name: "Masker", quantity: 2 },
    { id: "pinset", name: "Pinset", quantity: 1 },
    { id: "lampu_senter", name: "Lampu senter", quantity: 1 },
    { id: "gelas_cuci_mata", name: "Gelas untuk cuci mata", quantity: 1 },
    { id: "kantong_plastik_bersih", name: "Kantong plastik bersih", quantity: 1 },
    { id: "aquades_saline", name: "Aquades (100 ml lar. Saline)", quantity: 1 },
    { id: "povidon_iodin", name: "Povidon Iodin (60 ml)", quantity: 1 },
    { id: "alkohol_70", name: "Alkohol 70%", quantity: 1 },
    { id: "buku_panduan_p3k", name: "Buku panduan P3K di tempat kerja", quantity: 1 },
    { id: "catatan_logbook", name: "Catatan / logbook", quantity: 1 },
    { id: "daftar_isi_kotak", name: "Daftar isi kotak", quantity: 1 },
];

export const fireSafetyCardOptions = [
    { id: "apar", name: "APAR", title: "KARTU PEMELIHARAAN APAR" },
    { id: "smoke_detector", name: "Smoke Detector", title: "KARTU PEMELIHARAAN SMOKE DETECTOR" },
    { id: "fire_alarm", name: "Fire Alarm", title: "KARTU PEMELIHARAAN FIRE ALARM" },
];

export const fireSafetyLocationOptionsByType = {
    fire_alarm: [
        { id: "lobby_lantai_1", name: groupedLocationLabels.lobby_lantai_1 },
        { id: "area_office_lantai_2", name: groupedLocationLabels.area_office_lantai_2 },
        { id: "area_ruang_mesin", name: groupedLocationLabels.area_ruang_mesin },
        { id: "area_lantai_3", name: groupedLocationLabels.area_lantai_3 },
    ],
    smoke_detector: [
        { id: "lantai_1_lobby", name: "Lantai 1 - Lobby" },
        { id: "lantai_2_ruang_staff", name: "Lantai 2 - Ruang Staff" },
        { id: "lantai_2_ruang_direktur", name: "Lantai 2 - Ruang Direktur" },
        { id: "lantai_2_ruang_meeting", name: "Lantai 2 - Ruang Meeting" },
        { id: "lantai_2_pantry", name: "Lantai 2 - Pantry" },
        { id: "lantai_2_toilet", name: "Lantai 2 - Toilet" },
        { id: "lantai_3", name: "Lantai 3" },
        { id: "lantai_1_belakang", name: groupedLocationLabels.lantai_1_area_belakang },
    ],
    apar: [
        { id: "pos_security", name: groupedLocationLabels.pos_security },
        { id: "ruang_admin", name: groupedLocationLabels.ruang_admin },
        { id: "ruang_kontrol", name: groupedLocationLabels.ruang_kontrol },
        { id: "lobby_lantai_1", name: groupedLocationLabels.lobby_lantai_1 },
        { id: "anteroom_loading_dock", name: "Anteroom / Loading Dock" },
        { id: "ruang_mesin", name: "Ruang Mesin" },
        { id: "gudang_bahan_baku", name: "Gudang Bahan Baku" },
        { id: "area_office_lantai_2", name: groupedLocationLabels.area_office_lantai_2 },
        { id: "area_lantai_3", name: groupedLocationLabels.area_lantai_3 },
        { id: "halaman_depan", name: "Halaman Depan" },
        { id: "halaman_belakang", name: "Halaman Belakang" },
        { id: "area_luar_timur", name: "Area Luar Timur" },
        { id: "area_luar_barat", name: "Area Luar Barat" },
        { id: "area_kantin", name: "Area Kantin / Musholla" },
        { id: "ruang_baterai", name: groupedChecklistAreaLabels.ruang_baterai },
        { id: "gudang_bahan_jadi", name: "Gudang Bahan Jadi" },
    ],
};

export const fireSafetyItemsByType = {
    apar: [
        { id: "indikator_tekanan", name: "Indikator Tekanan" },
        { id: "pin_segel", name: "Pin/Segel" },
        { id: "selang", name: "Selang" },
        { id: "klem_selang", name: "Klem Selang" },
        { id: "handle", name: "Handle" },
        { id: "kondisi_fisik_tabung", name: "Kondisi Fisik Tabung" },
    ],
    smoke_detector: [
        { id: "alaram_menyala", name: "Alaram Menyala ketika ada asap di smoke detector" },
    ],
    fire_alarm: [
        { id: "terlihat_jelas", name: "Terlihat Jelas" },
        { id: "mudah_dijangkau", name: "Mudah Dijangkau" },
        { id: "tidak_terhalang_barang", name: "Tidak Terhalang Barang" },
        { id: "label_push_here", name: "Label Push Here Terbaca Jelas" },
        { id: "tombol_dapat_ditekan", name: "Tombol Dapat Ditekan saat Uji Fungsi" },
        { id: "dapat_direset", name: "Dapat direset Kembali setelah pengujian" },
        { id: "kondisi_bersih", name: "Kondisi Bersih dan Tidak Berdebu" },
    ],
};
